# Generated by Django 5.2 on 2025-05-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_tag_remove_map_title_remove_map_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.category'),
        ),
        migrations.AddField(
            model_name='map',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='maps', to='main_app.tag'),
        ),
    ]
